__collection-name__: quadruped-parameters

controller_dt     : 0.002
control_mode      : 2
training_control_mode      : 6
myValue           : 2222
stand_kd_cartesian: [2.5,2.5,2.5]
stand_kp_cartesian: [50, 50, 50]
testValue         : 23
cheater_mode      : 1

use_lcm_comm: 0
load_lcm_pd_controller: 0
nmpc_use_lcm: 0
nmpc_lcm_nonblocking: 0
nmpc_use_vel_control: 0
nmpc_adaptive_foot_placements: 1
use_vicon_state: 0
zero_yaw: 1
fix_body_height: 1

nmpc_jump_ctrl: 1
recompute_swingduration_every_step: 0

use_vicon_state: 0
#foot_height_sensor_noise      :  0.001
#foot_process_noise_position   :  0.002
#foot_sensor_noise_position    :  0.001
#foot_sensor_noise_velocity    :  0.1
#imu_process_noise_position    :  0.02
#imu_process_noise_velocity    :  0.02

kpCOM: [50,50,50]
kdCOM: [10,10,10]
kpBase: [300,200,100]
kdBase: [20,10,10]
use_rc: 1
#PATH_follow_waypoint       : 0
#PATH_move_waypoint         : 0
#PATH_x_max                 : 0.5
#PATH_y_max                 : 0.1
#PATH_yaw_max               : 1.25

Kd_joint          : [2, 1, 0.4]
Kp_joint          : [3, 3, 1]

Kp_body           : [200, 200, 100]
Kd_body           : [10, 10, 10]

Kp_foot           : [300, 300, 300]
Kd_foot           : [4, 4, 4]

Kp_ori            : [200, 200, 200]
Kd_ori            : [10, 10, 10]

# Kp_cam            : [0, 0, 0] # used for humanoid balance stand
# Kd_cam            : [5, 5, 5]
# Kp_clm            : [100, 100, 200]
# Kd_clm            : [5, 5, 10]

# Kp_cam            : [60, 60, 60] # successful for 13.5cm platform jump
# Kd_cam            : [4, 4, 2]
# Kp_clm            : [150, 150, 90]
# Kd_clm            : [9, 9, 6]

# Kp_cam            : [90, 90, 90] # tuning for left and right jump
# Kd_cam            : [4, 4, 2]
# Kp_clm            : [150, 150, 90]
# Kd_clm            : [9, 9, 6]

Kp_cam            : [150, 150, 110] # tuning for lateral jump
Kd_cam            : [4, 4, 2]
Kp_clm            : [150, 150, 90]
Kd_clm            : [9, 9, 6]

# Kp_cam            : [0, 40, 40] # successful for barrel roll
# Kd_cam            : [30, 3, 3]
# Kp_clm            : [45, 45, 45]
# Kd_clm            : [4, 4, 4]

# Kp_cam            : [100, 120, 100] # successful for hind leg stand
# Kd_cam            : [3, 20, 3]
# Kp_clm            : [200, 70, 540]
# Kd_clm            : [10, 3, 3]

cmpc_gait         : 9
cmpc_x_drag       : 3
cmpc_use_sparse   : 0
cmpc_bonus_swing  : 0
jcqp_alpha        : 1.5
jcqp_max_iter     : 10000
jcqp_rho          : 1e-07
jcqp_sigma        : 1e-08
jcqp_terminate    : 0.1
use_jcqp          : 0
use_wbc           : 1

# Swing leg parameters
Swing_Kp_cartesian : [350, 350, 75]
Swing_Kd_cartesian : [5.5, 5.5, 5.5]
Swing_Kp_joint     : [0, 0, 0]
Swing_Kd_joint     : [0.2, 0.2, 0.2]
Swing_step_offset  : [0,0.05,-0.003]
Swing_traj_height  : 0.07
Swing_use_tau_ff   : 0

# Two Leg Stance parameters
Q_pos             : [20, 20, 10000]
Q_vel             : [0, 0, 0]
Q_ori             : [1100, 1500, 400]
Q_ang             : [1, 3, 0.5]
R_control         : 1.5
R_prev            : 2.0
stance_legs       : 2
#stance_legs       : 4

# Acrobatics
acro_task         : 7

# RPC parameters
RPC_Q_p             : [10000, 10000, 100000]
RPC_Q_theta         : [5000, 10000, 2500]
RPC_Q_dp            : [10000, 10000, 500]
RPC_Q_dtheta        : [2.5, 2.5, 50]
RPC_R_r             : [350000, 350000, 0]
RPC_R_f             : [0.001, 0.001, 0.001]
RPC_H_r_trans       : [1, 2, 1]
RPC_H_r_rot         : [1, 1, 0]
RPC_H_theta0        : [1.25, 0, 0]
RPC_H_phi0          : [-0.12, 0.02, 0]
RPC_mass            : 10
RPC_inertia         : [0.07, 0.26, 0.242]
RPC_gravity         : [0, 0, -9.81]
RPC_mu              : 0.5
RPC_filter          : [0.5, 0.5, 0]
RPC_use_pred_comp   : 1
#RPC_use_async_filt  : 1
RPC_use_async_filt  : 0
RPC_visualize_pred  : 1
RPC_interface_type  : 1 # threaded: 0, LCM: 1, Neural_net: 2, periodic 3

# Desired state commands
des_p           : [0,0,0.26]
des_theta       : [0,0,0]
des_dp          : [0,0,0]
des_dtheta      : [0,0,0]
des_theta_max   : [0,0.4,0]
des_dp_max      : [1.0,0.4,0]
des_dtheta_max  : [0,0,2]

# Gait parameters
gait_type             : 4
gait_period_time      : 0.5
gait_switching_phase  : 0.5
gait_override         : 4
gait_max_leg_angle    : 15
gait_max_stance_time  : 0.25
gait_min_stance_time  : 0.1
gait_disturbance      : [0.05, 0.1, 0.3]
gait_recovery         : [0.05, 0.05, 0.2]

